// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCouwdJYhIqFxfsw8WLh6OTkdzyCfRWWw',
    appId: '1:202812955405:web:5d2e0d315dbd47647fae44',
    messagingSenderId: '202812955405',
    projectId: 'ecommerce-44529',
    authDomain: 'ecommerce-44529.firebaseapp.com',
    storageBucket: 'ecommerce-44529.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzu1gUNMw2CMrzeYMKwbCXa2ZYQ4H5X0',
    appId: '1:202812955405:android:fd149f19424dd4c77fae44',
    messagingSenderId: '202812955405',
    projectId: 'ecommerce-44529',
    storageBucket: 'ecommerce-44529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiztHUmPp477Krf8P-H5fiju_314K72y4',
    appId: '1:202812955405:ios:0b2309c2e71a3b687fae44',
    messagingSenderId: '202812955405',
    projectId: 'ecommerce-44529',
    storageBucket: 'ecommerce-44529.appspot.com',
    iosClientId: '202812955405-70913fji6da9lu6ne0b034h8gfrh11v9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiztHUmPp477Krf8P-H5fiju_314K72y4',
    appId: '1:202812955405:ios:b9f785c99d6764dd7fae44',
    messagingSenderId: '202812955405',
    projectId: 'ecommerce-44529',
    storageBucket: 'ecommerce-44529.appspot.com',
    iosClientId: '202812955405-d7aih6sirjv60c20gv6mltqes4upk4d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce1.RunnerTests',
  );
}
